# Site settings
title: xunyunyun
email: xunyunyun1990@163.com
description: xunyunyun's Blog
paginate: 10

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  xunyunyun
permalink: /:year/:month/:day/:title/

# Build settings
# markdown: kramdown

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html
